/**
 * The `retention` routine: scheduled pruning of historical session output.
 *
 * Arij never deleted any of it. The project specification has said so for a
 * while — "Unbounded table growth (reports, logs, artifacts) is not pruned
 * automatically; retention is a review finding waiting to happen" — and the
 * live database made it concrete: 489 MB, of which 395.5 MB is
 * `agent_session_chunks` across 126,953 rows generated by 531 sessions.
 *
 * This is the scheduling half; `lib/agent-sessions/chunk-prune.ts` is the
 * pruning half and owns the guarantees (terminal sessions only, forensic tail
 * and `last_non_empty_text` preserved). Kept apart because they answer
 * different questions — WHEN a project's history is pruned, and WHAT of it
 * survives — and because the pruner is worth testing against a raw database
 * handle with no scheduler in the way.
 *
 * The routine is daily, so it goes through the same `last_run_at` claim as
 * `night_run` and `github_issue_sync`: the scheduler writes the timestamp
 * before it calls the action, which is the restart-safe half of the
 * anti-double-run guard. A prune interrupted halfway is not replayed the same
 * day; the next day's run simply finishes the backlog, because pruning an
 * already-pruned stream is a no-op.
 *
 * ## Reclaiming the space: VACUUM
 *
 * Deleting rows returns their pages to SQLite's free list; it does not return
 * them to the filesystem. Only `VACUUM` rewrites the database file, and on a
 * half-gigabyte database that is a multi-second exclusive rewrite on the one
 * synchronous connection every request shares — so it runs ONCE, after the
 * first prune that actually freed something, and never again on a schedule.
 * The claim is durable (`retentionVacuumedAt` in the routine config), so a
 * restart cannot replay it.
 *
 * To reclaim again later — after a one-off retention-window change, say —
 * run it by hand against a stopped server:
 *
 *     sqlite3 data/arij.db 'VACUUM;'
 *
 * or clear `retentionVacuumedAt` from the routine's config and let the next
 * prune redo it. Set `config.vacuum` to `false` to opt out entirely.
 */

import { eq, inArray } from "drizzle-orm";
import { db, sqlite } from "@/lib/db";
import { routines, settings, type Routine } from "@/lib/db/schema";
import type { AgentSessionStreamType } from "@/lib/agent-sessions/chunks";
import {
  createSessionChunkPruner,
  type SessionChunkPruneResult,
} from "@/lib/agent-sessions/chunk-prune";
import {
  FORENSIC_OUTPUT_TAIL_MAX_CHARS,
  FORENSIC_RAW_TAIL_MAX_CHARS,
} from "@/lib/pipeline/constants";
import type { RoutineActionResult } from "@/lib/routines/actions";
import {
  parseRoutineConfig,
  RETENTION_VACUUMED_AT_CONFIG_KEY,
} from "@/lib/routines/constants";

/** Global default window, overridable per project. */
export const SESSION_CHUNK_RETENTION_DAYS_SETTING_KEY =
  "session_chunk_retention_days";

/**
 * Built-in retention window in days. Override globally with
 * `session_chunk_retention_days`, or per project with
 * `session_chunk_retention_days:<projectId>`.
 *
 * 30 days is chosen against the readers, not picked round. The only things
 * that read a session's chunks back mechanically are the forensic collector
 * (`readChunkTail`, which runs minutes after the session it diagnoses died)
 * and the Arij-action scan behind the session detail. Everything that reasons
 * over older history — Dreaming's rolling 14 days, smart dispatch's 30-day
 * reliability scores, the recurring-failure digest — reads
 * `last_non_empty_text`, comments, findings and outcome columns, none of
 * which a prune touches. So the window is sized for the remaining reader, a
 * human scrolling back through the Sessions page, and for that the retained
 * tail under its marker is enough.
 *
 * It is deliberately the conservative end. Measured on a snapshot of the live
 * database (1.02 GB, 934 sessions, 257,412 chunk rows holding 867.5 MiB), the
 * whole of that content was under 30 days old and a 30-day pass reclaimed
 * NOTHING; a 7-day pass pruned 192 sessions, deleted 148,932 chunk rows, took
 * the content to 72.7 MiB and the file to 176.7 MiB. A project generating
 * output at that rate should lower the setting rather than expect the default
 * to hold the file down.
 */
export const DEFAULT_SESSION_CHUNK_RETENTION_DAYS = 30;

/** Chunk rows one run may delete before it leaves the rest for tomorrow. */
export const DEFAULT_MAX_DELETED_CHUNKS_PER_RUN = 50_000;

/**
 * Characters kept at the end of the `response` stream.
 *
 * Nothing in Arij reads this stream back mechanically — it is the transcript
 * the session detail renders. The budget exists so a pruned session shows its
 * closing exchange under the marker instead of an empty panel.
 */
export const RETAINED_RESPONSE_TAIL_CHARS = 4000;

/**
 * Per-stream retention budget.
 *
 * `raw` and `output` are DERIVED from the forensic reader's own tail limits
 * rather than restated, so the amount kept and the amount read can never
 * drift apart: `readChunkTail` slices the last N characters of the stream, so
 * keeping at least N makes a forensic prompt identical before and after a
 * prune.
 */
export const SESSION_CHUNK_RETAINED_TAIL_CHARS: Record<
  AgentSessionStreamType,
  number
> = {
  raw: FORENSIC_RAW_TAIL_MAX_CHARS,
  output: FORENSIC_OUTPUT_TAIL_MAX_CHARS,
  response: RETAINED_RESPONSE_TAIL_CHARS,
};

export function sessionChunkRetentionDaysSettingKey(projectId: string): string {
  return `${SESSION_CHUNK_RETENTION_DAYS_SETTING_KEY}:${projectId}`;
}

/**
 * A stored window is either raw (`45`) or JSON (`"45"`, `45`). Anything that
 * is not a positive integer — including `0`, which would prune a session the
 * moment it ended — falls through to the next source rather than being
 * honoured, because the failure mode of a bad retention value is deletion.
 */
function parseRetentionDays(value: string | undefined): number | null {
  if (value === undefined) return null;
  const raw = value.trim();
  if (!raw) return null;
  let parsed: unknown = Number(raw);
  if (!Number.isFinite(parsed as number)) {
    try {
      parsed = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  const days = typeof parsed === "string" ? Number(parsed) : parsed;
  return typeof days === "number" && Number.isInteger(days) && days > 0
    ? days
    : null;
}

/** Project override -> global override -> built-in default. */
export function resolveSessionChunkRetentionDays(projectId: string): number {
  try {
    const projectKey = sessionChunkRetentionDaysSettingKey(projectId);
    const rows = db
      .select({ key: settings.key, value: settings.value })
      .from(settings)
      .where(
        inArray(settings.key, [
          projectKey,
          SESSION_CHUNK_RETENTION_DAYS_SETTING_KEY,
        ]),
      )
      .all();
    const byKey = new Map(rows.map((row) => [row.key, row.value]));
    return (
      parseRetentionDays(byKey.get(projectKey)) ??
      parseRetentionDays(byKey.get(SESSION_CHUNK_RETENTION_DAYS_SETTING_KEY)) ??
      DEFAULT_SESSION_CHUNK_RETENTION_DAYS
    );
  } catch {
    // A settings read failure must never widen what a prune deletes.
    return DEFAULT_SESSION_CHUNK_RETENTION_DAYS;
  }
}

export interface RetentionDeps {
  resolveRetentionDays(projectId: string): number;
  prune(options: {
    projectId: string;
    cutoff: string;
    maxDeletedChunks: number;
    prunedAt: string;
  }): SessionChunkPruneResult;
  vacuum(): void;
  claimVacuum(routineId: string, at: string): void;
}

export const defaultRetentionDeps: RetentionDeps = {
  resolveRetentionDays: resolveSessionChunkRetentionDays,
  prune: (options) =>
    createSessionChunkPruner(sqlite).prune({
      ...options,
      tailChars: SESSION_CHUNK_RETAINED_TAIL_CHARS,
    }),
  // Deliberately on the raw handle and outside any transaction: SQLite
  // refuses VACUUM inside one.
  vacuum: () => {
    sqlite.exec("VACUUM");
  },
  claimVacuum: (routineId, at) => {
    const row = db
      .select({ config: routines.config })
      .from(routines)
      .where(eq(routines.id, routineId))
      .get();
    if (!row) return;
    let config: Record<string, unknown> = {};
    try {
      const parsed = JSON.parse(row.config) as unknown;
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        config = parsed as Record<string, unknown>;
      }
    } catch {
      // A malformed config must not stop the claim from being recorded.
    }
    db.update(routines)
      .set({
        config: JSON.stringify({
          ...config,
          [RETENTION_VACUUMED_AT_CONFIG_KEY]: at,
        }),
      })
      .where(eq(routines.id, routineId))
      .run();
  },
};

function positiveInteger(
  config: Record<string, unknown>,
  key: string,
  fallback: number,
): number {
  const value = config[key];
  if (value === undefined) return fallback;
  if (!Number.isInteger(value) || (value as number) < 1) {
    throw new Error(`Routine config.${key} must be a positive integer`);
  }
  return value as number;
}

function booleanOption(
  config: Record<string, unknown>,
  key: string,
  fallback: boolean,
): boolean {
  const value = config[key];
  if (value === undefined) return fallback;
  if (typeof value !== "boolean") {
    throw new Error(`Routine config.${key} must be a boolean`);
  }
  return value as boolean;
}

/** Characters are close enough to bytes for a status line to be useful. */
function formatChars(chars: number): string {
  if (chars < 1024) return `${chars} characters`;
  if (chars < 1024 * 1024) return `${(chars / 1024).toFixed(1)} KiB`;
  return `${(chars / (1024 * 1024)).toFixed(1)} MiB`;
}

export function retentionCutoff(now: Date, retentionDays: number): string {
  return new Date(now.getTime() - retentionDays * 86_400_000).toISOString();
}

/**
 * Prune one project's terminal session output, then reclaim the freed pages
 * once. Never throws for a "nothing to do" outcome — that is a `skipped`
 * result, which the scheduler records without an alarming notification.
 */
export async function runRetentionRoutine(
  routine: Routine,
  deps: RetentionDeps = defaultRetentionDeps,
  now: Date = new Date(),
): Promise<RoutineActionResult> {
  const config = parseRoutineConfig(routine);
  const maxDeletedChunks = positiveInteger(
    config,
    "maxDeletedChunks",
    DEFAULT_MAX_DELETED_CHUNKS_PER_RUN,
  );
  const vacuumAllowed = booleanOption(config, "vacuum", true);
  const alreadyVacuumed =
    typeof config[RETENTION_VACUUMED_AT_CONFIG_KEY] === "string";

  const retentionDays = deps.resolveRetentionDays(routine.projectId);
  const prunedAt = now.toISOString();
  const result = deps.prune({
    projectId: routine.projectId,
    cutoff: retentionCutoff(now, retentionDays),
    maxDeletedChunks,
    prunedAt,
  });

  const targetUrl = `/projects/${routine.projectId}/sessions`;
  if (result.prunedSessions === 0) {
    return {
      status: "skipped",
      message: `Nothing to prune: ${result.scannedSessions} terminal session${
        result.scannedSessions === 1 ? "" : "s"
      } older than ${retentionDays} days are already inside their retained tail.`,
      targetUrl,
      shouldNotify: false,
    };
  }

  let vacuumed = false;
  if (vacuumAllowed && !alreadyVacuumed) {
    // Claim BEFORE the rewrite, exactly like the scheduler's own run claim: a
    // crash mid-VACUUM must not hand the next boot a second multi-second
    // exclusive rewrite. SQLite rolls the file back on its own.
    deps.claimVacuum(routine.id, prunedAt);
    deps.vacuum();
    vacuumed = true;
  }

  const parts = [
    `Pruned ${result.prunedSessions} session${
      result.prunedSessions === 1 ? "" : "s"
    } older than ${retentionDays} days`,
    `${result.deletedChunks} chunk${
      result.deletedChunks === 1 ? "" : "s"
    } deleted, ${formatChars(result.reclaimedChars)} of content freed`,
  ];
  if (result.truncatedChunks > 0) {
    parts.push(`${result.truncatedChunks} trimmed to their retained tail`);
  }
  if (result.preservedLastTexts > 0) {
    parts.push(
      `${result.preservedLastTexts} final response${
        result.preservedLastTexts === 1 ? "" : "s"
      } preserved on the session row`,
    );
  }
  if (vacuumed) parts.push("database vacuumed");
  if (result.reachedDeleteBudget) {
    parts.push(`stopped at the ${maxDeletedChunks}-chunk budget for this run`);
  }

  return {
    status: "completed",
    message: `${parts.join("; ")}.`,
    targetUrl,
  };
}
