/* GENERATED by scripts/i18n/build-messages-index.mjs — do not edit by hand.
 * Add lib/i18n/messages/<locale>/<Namespace>.json and run `npm run i18n:index`. */

import en_Format from "./en/Format.json";
import en_Nav from "./en/Nav.json";
import en_Settings from "./en/Settings.json";
import en_Spec from "./en/Spec.json";
import en_TopBar from "./en/TopBar.json";
import fr_Format from "./fr/Format.json";
import fr_Nav from "./fr/Nav.json";
import fr_Settings from "./fr/Settings.json";
import fr_Spec from "./fr/Spec.json";
import fr_TopBar from "./fr/TopBar.json";

export const en = {
  Format: en_Format,
  Nav: en_Nav,
  Settings: en_Settings,
  Spec: en_Spec,
  TopBar: en_TopBar,
};

export const fr = {
  Format: fr_Format,
  Nav: fr_Nav,
  Settings: fr_Settings,
  Spec: fr_Spec,
  TopBar: fr_TopBar,
};
